random_state: 42

logistic_regression:
  solver: lbfgs
  penalty: l2
  C: 0.8
  max_iter: 500
  class_weight: balanced

random_forest:
  n_estimators: 300
  max_depth: 10
  min_samples_leaf: 20
  max_features: sqrt
  class_weight: balanced

hgbt:
  learning_rate: 0.05
  max_depth: 5
  max_bins: 255
  l2_regularization: 0.1
  max_samples: 0.8
